# Generated by Django 4.2.2 on 2023-09-13 22:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profesores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaHora', models.DateTimeField()),
                ('descripcion', models.TextField()),
                ('id_profesor', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='profesores.profesor')),
            ],
        ),
    ]
