# Generated by Django 4.2.6 on 2023-11-04 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0002_alter_personal_direccion_p_alter_personal_legajo_p_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personal',
            name='copiaDNI_p',
            field=models.ImageField(blank=True, null=True, upload_to='personal/images/'),
        ),
        migrations.AlterField(
            model_name='personal',
            name='fecha_nac_p',
            field=models.DateField(blank=True, null=True),
        ),
    ]
