# Generated by Django 4.2.2 on 2023-11-08 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnado', '0011_alter_alumno_direccion_alter_alumno_id_curso_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumno',
            name='condicion',
            field=models.IntegerField(choices=[[0, 'Regular'], [1, 'Semipresencial'], [2, 'Libre']], null=True, verbose_name='Condición'),
        ),
        migrations.AddField(
            model_name='alumno',
            name='turno',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Turno'),
        ),
    ]
