# Generated by Django 4.2.2 on 2023-11-09 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnado', '0013_alumno_cantidad_asistencias'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumno',
            name='cantidad_inasistencias',
            field=models.IntegerField(default=0),
        ),
    ]
