# Generated by Django 4.2.2 on 2023-11-08 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curso', '0005_alter_curso_id_materia'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='cantidad_clases',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
