# Generated by Django 4.2.2 on 2023-11-09 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curso', '0006_curso_cantidad_clases'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='Annio',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='curso',
            name='Division',
            field=models.CharField(max_length=30),
        ),
    ]
